name: Bug report (code or build issues)
description: Let us know about an issue you experienced.
title: '[CODE BUG]: '
labels: ['bug','devhub']
body:
  - type: markdown
    attributes:
      value: |
        Thank you so much for taking the time to report a problem!
  - type: textarea
    id: bug
    attributes:
      label: Bug report for compiling, code snippets, templates, etc.
      description: What happened?
      placeholder: Describe the problem.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the problem
      description: Provide the steps that led to the discovery of the issue.
      placeholder: Describe what you were doing so we can reproduce the problem.
    validations:
      required: false
  - type: input
    id: contact
    attributes:
      label: Contact details (optional)
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: markdown
    attributes:
      value: 'Thanks again for completing this report!'
