name: Feedback form template
description: Submit your feedback to help us improve.
title: '[Feedback Submission]: '
labels: ['feedback']
body:
  - type: markdown
    attributes:
      value: |
        Thank you so much for taking the time to submit your feedback!
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other (please write below)
    validations:
      required: false
  - type: textarea
    id: feedback
    attributes:
      label: Feedback
      description: Did something go wrong or have a suggestion for improving this site?
      placeholder: Describe what you would like to see changed.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the problem (optional)
      description: Provide the steps that led to the discovery of the issue.
      placeholder: Describe what you were doing so we can reproduce the problem.
    validations:
      required: false
  - type: input
    id: contact
    attributes:
      label: Contact details (optional)
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: markdown
    attributes:
      value: 'Thanks for completing our form!'
