# Navigation:
nav:
  - Quick Start:
      - 'quick-start'
  - Docs:
      - '/main-docs/' #category page link
      - 'Why Substrate?': '/main-docs/why-substrate/choose-a-dev-platform/' #page link
  - Reference:
      - 'Glossary': '/reference/glossary/'
      - 'Why Substrate?': '/main-docs/why-substrate/choose-a-dev-platform/'
      - 'Build a local blockchain': '/tutorials/build-blockchain/'
  - Tutorials:
      - '/tutorials/'
      - 'Build a local blockchain': '/tutorials/build-blockchain/'
  - Example External: 'https://example.com'
