# Navigation:
nav:
  - Quick Start:
      - '/quick-start/'
  - Docs:
      - '/main-docs/' #category page link
      - 'Why Substrate?': '/main-docs/why-substrate/choose-a-dev-platform/' #page link
  - Reference:
      - 'Glossary': '/reference/glossary/'
  - Tutorials:
      - '/tutorials/'
      - 'Build a local blockchain': '/tutorials/build-blockchain/'
      - 'Initiate a Forkless Runtime Upgrade': '/tutorials/forkless-upgrades/'
